# Generated by Django 3.0.3 on 2020-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avator',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
